import 'package:flutter/cupertino.dart';

class Anwser {
  String anwser;
  bool index;
  Anwser(this.anwser, this.index);
}

List<Anwser> fakeAnwer() {
  List<Anwser> list = <Anwser>[];
  list.add(new Anwser("Trả về một đối tượn", false));
  list.add(new Anwser("Thêm một phần tử vào", true));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));
  list.add(new Anwser("Trả về một đối tượn", true));
  list.add(new Anwser("Thêm một phần tử vào", false));
  list.add(new Anwser("Chèn một phần tử vào ", false));
  list.add(new Anwser("Xóa bỏ phần tử đầu", false));
  list.add(new Anwser("America", true));
  list.add(new Anwser("Flutter", false));
  list.add(new Anwser("ủa Googl", false));
  list.add(new Anwser(" dựng", false));
  list.add(new Anwser("lutter hầu ", true));
  list.add(new Anwser("hể phân ", false));
  list.add(new Anwser("ững tinh chỉnh nhỏ", false));
  list.add(new Anwser("framework ", false));

  return list;
}
